/*
 * SW4_mingwSyscalls.c -- generated by SysWhispers4
 * DO NOT EDIT -- regenerate with syswhispers.py
 *
 * Resolution : halos_gate
 * Method     : indirect
 * Arch       : x64
 */
#include "SW4_mingwSyscalls.h"
#include <stddef.h>
#include <string.h>

/* =========================================================================
 *  Constants
 * ========================================================================= */
#define SW4_mingw_FUNC_COUNT    21U
#define SW4_mingw_MAX_EXPORTS   1024U
#define SW4_mingw_GADGET_POOL   0U
#define SW4_mingw_GADGET_MASK   (-1U)  /* pool must be power of 2 */

#define SW4_mingw_DECRYPT(v) (v)

/* DJB2 hashes of function names (compile-time) */
static const DWORD SW4_mingw_FuncHashes[SW4_mingw_FUNC_COUNT] = {
    0xF0146CE2U,  /* NtAllocateVirtualMemory */
    0xAF9FFAABU,  /* NtFreeVirtualMemory */
    0x411B83A2U,  /* NtWriteVirtualMemory */
    0xE88BED2DU,  /* NtReadVirtualMemory */
    0xCD363694U,  /* NtProtectVirtualMemory */
    0xBB485288U,  /* NtCreateThreadEx */
    0xAED3CBA0U,  /* NtOpenProcess */
    0x1E8A3A05U,  /* NtOpenThread */
    0xE03939BBU,  /* NtSuspendThread */
    0xDAE08088U,  /* NtResumeThread */
    0xBFC8B678U,  /* NtGetContextThread */
    0xD8FDE5ECU,  /* NtSetContextThread */
    0x7473FDF5U,  /* NtUnmapViewOfSection */
    0xDA22F84EU,  /* NtMapViewOfSection */
    0x01D8A572U,  /* NtCreateSection */
    0x4D230412U,  /* NtQueueApcThread */
    0x21F4488FU,  /* NtQueueApcThreadEx */
    0x98B61166U,  /* NtAlertResumeThread */
    0x9AD13387U,  /* NtTestAlert */
    0xF866D229U,  /* NtClose */
    0xB01F5300U,  /* NtWaitForSingleObject */
};

/* =========================================================================
 *  Runtime tables (populated by SW4_mingw_Initialize)
 * ========================================================================= */
DWORD  SW4_mingw_SsnTable[SW4_mingw_FUNC_COUNT];          /* SSN for each function */
PVOID SW4_mingw_SyscallAddrTable[SW4_mingw_FUNC_COUNT];  /* addr of syscall;ret in ntdll */

/* =========================================================================
 *  DJB2 hash (matches compile-time hashes above)
 * ========================================================================= */
static DWORD SW4_mingw_HashStr(const char* s) {
    DWORD h = 0x1505U;
    while (*s) { h = ((h << 5) + h) ^ (unsigned char)*s++; }
    return h;
}

/* =========================================================================
 *  Locate ntdll.dll via PEB (no Win32 API calls)
 * ========================================================================= */
static PVOID SW4_mingw_GetNtdllBase(VOID) {
    PPEB pPeb = (PPEB)__readgsqword(0x60);
    PPEB_LDR_DATA   pLdr   = pPeb->Ldr;
    PLIST_ENTRY     pHead  = &pLdr->InMemoryOrderModuleList;
    PLIST_ENTRY     pEntry = pHead->Flink; /* exe */
    pEntry = pEntry->Flink;               /* ntdll (always 2nd in InMemoryOrder) */
    PLDR_DATA_TABLE_ENTRY pMod =
        CONTAINING_RECORD(pEntry, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
    return pMod->DllBase;
}

/* Get own image base via PEB */
static PVOID SW4_mingw_GetOwnImageBase(VOID) {
    PPEB pPeb = (PPEB)__readgsqword(0x60);
    PLIST_ENTRY pHead = &pPeb->Ldr->InMemoryOrderModuleList;
    PLDR_DATA_TABLE_ENTRY pMod =
        CONTAINING_RECORD(pHead->Flink, LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
    return pMod->DllBase;
}

/* =========================================================================
 *  EAT utility: find export by hash
 * ========================================================================= */
static PVOID SW4_mingw_GetProcByHash(PVOID pModule, DWORD dwHash) {
    PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
    PIMAGE_NT_HEADERS pNt  = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
    PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
        (PBYTE)pModule +
        pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);

    PDWORD pFnArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfFunctions);
    PDWORD pNmArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfNames);
    PWORD  pOrArr = (PWORD) ((PBYTE)pModule + pExp->AddressOfNameOrdinals);

    for (DWORD i = 0; i < pExp->NumberOfNames; i++) {
        const char* pName = (const char*)((PBYTE)pModule + pNmArr[i]);
        if (SW4_mingw_HashStr(pName) == dwHash)
            return (PVOID)((PBYTE)pModule + pFnArr[pOrArr[i]]);
    }
    return NULL;
}

/* Find export by name string (for VEH-based methods) */
static PVOID SW4_mingw_GetProcByName(PVOID pModule, const char* szName) {
    PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
    PIMAGE_NT_HEADERS pNt  = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
    PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
        (PBYTE)pModule +
        pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);

    PDWORD pFnArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfFunctions);
    PDWORD pNmArr = (PDWORD)((PBYTE)pModule + pExp->AddressOfNames);
    PWORD  pOrArr = (PWORD) ((PBYTE)pModule + pExp->AddressOfNameOrdinals);

    for (DWORD i = 0; i < pExp->NumberOfNames; i++) {
        const char* pName = (const char*)((PBYTE)pModule + pNmArr[i]);
        DWORD j = 0;
        while (pName[j] && szName[j] && pName[j] == szName[j]) j++;
        if (pName[j] == 0 && szName[j] == 0)
            return (PVOID)((PBYTE)pModule + pFnArr[pOrArr[i]]);
    }
    return NULL;
}

/* =========================================================================
 *  Insertion-sort helper for export arrays (avoids qsort dependency)
 * ========================================================================= */
static VOID SW4_mingw_SortExports(PSW4_mingw_EXPORT arr, DWORD n) {
    for (DWORD i = 1; i < n; i++) {
        SW4_mingw_EXPORT key = arr[i];
        LONG j = (LONG)i - 1;
        while (j >= 0 && arr[j].Address > key.Address) {
            arr[j + 1] = arr[j];
            j--;
        }
        arr[j + 1] = key;
    }
}

/* =========================================================================
 *  Parse PE section headers (used by multiple evasion techniques)
 * ========================================================================= */
static PIMAGE_SECTION_HEADER SW4_mingw_FindSection(PVOID pModule, const char* name) {
    PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pModule;
    PIMAGE_NT_HEADERS pNt  = (PIMAGE_NT_HEADERS)((PBYTE)pModule + pDos->e_lfanew);
    PIMAGE_SECTION_HEADER pSec = IMAGE_FIRST_SECTION(pNt);

    for (WORD i = 0; i < pNt->FileHeader.NumberOfSections; i++, pSec++) {
        BOOL match = TRUE;
        for (int j = 0; name[j]; j++) {
            if (pSec->Name[j] != (BYTE)name[j]) { match = FALSE; break; }
        }
        if (match) return pSec;
    }
    return NULL;
}

/* =========================================================================
 *  Halo's Gate SSN resolution
 *  Extends Hell's Gate: when a stub is hooked (E9 JMP), searches neighboring
 *  stubs in the sorted export list and infers SSN by +/- offset.
 * ========================================================================= */
static BOOL SW4_mingw_HalosGate(PVOID pNtdll) {
    /* Build sorted export list first */
    PIMAGE_DOS_HEADER pDos = (PIMAGE_DOS_HEADER)pNtdll;
    PIMAGE_NT_HEADERS pNt  = (PIMAGE_NT_HEADERS)((PBYTE)pNtdll + pDos->e_lfanew);
    PIMAGE_EXPORT_DIRECTORY pExp = (PIMAGE_EXPORT_DIRECTORY)(
        (PBYTE)pNtdll +
        pNt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_EXPORT].VirtualAddress);
    PDWORD pFnArr = (PDWORD)((PBYTE)pNtdll + pExp->AddressOfFunctions);
    PDWORD pNmArr = (PDWORD)((PBYTE)pNtdll + pExp->AddressOfNames);
    PWORD  pOrArr = (PWORD )((PBYTE)pNtdll + pExp->AddressOfNameOrdinals);

    SW4_mingw_EXPORT exports[SW4_mingw_MAX_EXPORTS];
    DWORD count = 0;
    for (DWORD i = 0; i < pExp->NumberOfNames && count < SW4_mingw_MAX_EXPORTS; i++) {
        const char* n = (const char*)((PBYTE)pNtdll + pNmArr[i]);
        if (n[0] == 'N' && n[1] == 't') {
            exports[count].Address = (PVOID)((PBYTE)pNtdll + pFnArr[pOrArr[i]]);
            exports[count].Hash    = SW4_mingw_HashStr(n);
            exports[count].Ordinal = i;
            count++;
        }
    }
    SW4_mingw_SortExports(exports, count);

    for (DWORD fi = 0; fi < SW4_mingw_FUNC_COUNT; fi++) {
        /* Find this function in sorted list */
        LONG myIdx = -1;
        for (DWORD ei = 0; ei < count; ei++) {
            if (exports[ei].Hash == SW4_mingw_FuncHashes[fi]) { myIdx = (LONG)ei; break; }
        }
        if (myIdx < 0) continue;

        PBYTE pFn = (PBYTE)exports[myIdx].Address;
        BOOL resolved = FALSE;

        /* Check if clean (unhooked) */
        for (DWORD k = 0; k < 32 && !resolved; k++) {
            if (pFn[k] == 0x4Cu && pFn[k+1u] == 0x8Bu &&
                pFn[k+2u] == 0xD1u && pFn[k+3u] == 0xB8u) {
                DWORD ssn = (DWORD)pFn[k+4u] | ((DWORD)pFn[k+5u] << 8u);
                SW4_mingw_SsnTable[fi] = ssn;
            /* Locate syscall;ret gadget in this stub */
            if (!SW4_mingw_SyscallAddrTable[fi]) {
                PBYTE pS = pFn;
                for (DWORD sk = 0; sk < 32; sk++) {
                    if (pS[sk] == 0x0Fu && pS[sk + 1u] == 0x05u) {
                        SW4_mingw_SyscallAddrTable[fi] = pS + sk;
                        break;
                    }
                }
            }
                resolved = TRUE;
            }
        }

        /* Hooked: scan neighbors (up to 8 stubs away) */
        if (!resolved) {
            for (LONG delta = 1; delta <= 8 && !resolved; delta++) {
                for (LONG dir = -1; dir <= 1 && !resolved; dir += 2) {
                    LONG ni = myIdx + delta * dir;
                    if (ni < 0 || ni >= (LONG)count) continue;
                    PBYTE pN = (PBYTE)exports[ni].Address;
                    for (DWORD k = 0; k < 32 && !resolved; k++) {
                        if (pN[k] == 0x4Cu && pN[k+1u] == 0x8Bu &&
                            pN[k+2u] == 0xD1u && pN[k+3u] == 0xB8u) {
                            DWORD neighborSsn = (DWORD)pN[k+4u] | ((DWORD)pN[k+5u] << 8u);
                            /* Our SSN = neighbor SSN - (sorted_index_delta) */
                            DWORD ssn = neighborSsn - (DWORD)(delta * dir);
                            SW4_mingw_SsnTable[fi] = ssn;
            /* Locate syscall;ret gadget in this stub */
            if (!SW4_mingw_SyscallAddrTable[fi]) {
                PBYTE pS = pFn;
                for (DWORD sk = 0; sk < 32; sk++) {
                    if (pS[sk] == 0x0Fu && pS[sk + 1u] == 0x05u) {
                        SW4_mingw_SyscallAddrTable[fi] = pS + sk;
                        break;
                    }
                }
            }
                            resolved = TRUE;
                        }
                    }
                }
            }
        }
    }
    return TRUE;
}



/* =========================================================================
 *  SW4_mingw_Initialize -- call once at process/shellcode startup
 * ========================================================================= */
BOOL SW4_mingw_Initialize(VOID) {
    PVOID pNtdll = SW4_mingw_GetNtdllBase();
    if (!pNtdll) return FALSE;

    return SW4_mingw_HalosGate(pNtdll);
}