; SW4_msvcSyscalls.asm -- generated by SysWhispers4
; Method     : indirect
; Resolution : freshycalls
; Arch       : x64 / MASM (ml64.exe)
;
; Build: cl /nologo ... SW4_msvcSyscalls.c SW4_msvcSyscalls.asm
;        (ensure MASM64 is enabled in project settings)

OPTION DOTNAME

.data
    EXTERN SW4_msvc_SsnTable:DWORD
    EXTERN SW4_msvc_SyscallAddrTable:QWORD

.code

; --- SW4_msvc_NtAllocateVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtAllocateVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 0]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 0]     ; -> ntdll gadget
SW4_msvc_NtAllocateVirtualMemory ENDP


; --- SW4_msvc_NtFreeVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtFreeVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 4]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 8]     ; -> ntdll gadget
SW4_msvc_NtFreeVirtualMemory ENDP


; --- SW4_msvc_NtWriteVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtWriteVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 8]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 16]     ; -> ntdll gadget
SW4_msvc_NtWriteVirtualMemory ENDP


; --- SW4_msvc_NtReadVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtReadVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 12]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 24]     ; -> ntdll gadget
SW4_msvc_NtReadVirtualMemory ENDP


; --- SW4_msvc_NtProtectVirtualMemory (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtProtectVirtualMemory PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 16]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 32]     ; -> ntdll gadget
SW4_msvc_NtProtectVirtualMemory ENDP


; --- SW4_msvc_NtCreateThreadEx (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtCreateThreadEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 20]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 40]     ; -> ntdll gadget
SW4_msvc_NtCreateThreadEx ENDP


; --- SW4_msvc_NtOpenProcess (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtOpenProcess PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 24]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 48]     ; -> ntdll gadget
SW4_msvc_NtOpenProcess ENDP


; --- SW4_msvc_NtOpenThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtOpenThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 28]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 56]     ; -> ntdll gadget
SW4_msvc_NtOpenThread ENDP


; --- SW4_msvc_NtSuspendThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtSuspendThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 32]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 64]     ; -> ntdll gadget
SW4_msvc_NtSuspendThread ENDP


; --- SW4_msvc_NtResumeThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtResumeThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 36]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 72]     ; -> ntdll gadget
SW4_msvc_NtResumeThread ENDP


; --- SW4_msvc_NtGetContextThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtGetContextThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 40]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 80]     ; -> ntdll gadget
SW4_msvc_NtGetContextThread ENDP


; --- SW4_msvc_NtSetContextThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtSetContextThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 44]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 88]     ; -> ntdll gadget
SW4_msvc_NtSetContextThread ENDP


; --- SW4_msvc_NtUnmapViewOfSection (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtUnmapViewOfSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 48]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 96]     ; -> ntdll gadget
SW4_msvc_NtUnmapViewOfSection ENDP


; --- SW4_msvc_NtMapViewOfSection (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtMapViewOfSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 52]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 104]     ; -> ntdll gadget
SW4_msvc_NtMapViewOfSection ENDP


; --- SW4_msvc_NtCreateSection (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtCreateSection PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 56]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 112]     ; -> ntdll gadget
SW4_msvc_NtCreateSection ENDP


; --- SW4_msvc_NtQueueApcThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtQueueApcThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 60]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 120]     ; -> ntdll gadget
SW4_msvc_NtQueueApcThread ENDP


; --- SW4_msvc_NtQueueApcThreadEx (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtQueueApcThreadEx PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 64]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 128]     ; -> ntdll gadget
SW4_msvc_NtQueueApcThreadEx ENDP


; --- SW4_msvc_NtAlertResumeThread (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtAlertResumeThread PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 68]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 136]     ; -> ntdll gadget
SW4_msvc_NtAlertResumeThread ENDP


; --- SW4_msvc_NtTestAlert (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtTestAlert PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 72]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 144]     ; -> ntdll gadget
SW4_msvc_NtTestAlert ENDP


; --- SW4_msvc_NtClose (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtClose PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 76]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 152]     ; -> ntdll gadget
SW4_msvc_NtClose ENDP


; --- SW4_msvc_NtWaitForSingleObject (indirect: jmp to syscall;ret in ntdll) ---
SW4_msvc_NtWaitForSingleObject PROC
    mov r10, rcx                            ; syscall ABI: arg1 -> r10
    mov eax, DWORD PTR [SW4_msvc_SsnTable + 80]  ; load SSN
    jmp QWORD PTR [SW4_msvc_SyscallAddrTable + 160]     ; -> ntdll gadget
SW4_msvc_NtWaitForSingleObject ENDP


END
