/*
 * SW4_mingwSyscalls_Types.h -- generated by SysWhispers4
 * DO NOT EDIT -- regenerate with syswhispers.py
 *
 * Resolution : halos_gate
 * Method     : indirect
 * Arch       : x64
 * Compiler   : mingw
 */
#pragma once
#ifndef SW4_mingw_SYSCALLS_TYPES_H
#define SW4_mingw_SYSCALLS_TYPES_H

#include <windows.h>
#include <winternl.h>
#ifdef __GNUC__
# include <intrin.h>  /* __readgsqword for MinGW-w64 */
#endif

/* =========================================================================
 *  SW4 -- NT type definitions not in winternl.h / ntdef.h
 * ========================================================================= */

#ifndef NT_SUCCESS
# define NT_SUCCESS(Status)  (((NTSTATUS)(Status)) >= 0)
#endif

#ifndef STATUS_SUCCESS
# define STATUS_SUCCESS      ((NTSTATUS)0x00000000L)
#endif

#ifndef STATUS_ACCESS_DENIED
# define STATUS_ACCESS_DENIED ((NTSTATUS)0xC0000022L)
#endif

#ifndef STATUS_INFO_LENGTH_MISMATCH
# define STATUS_INFO_LENGTH_MISMATCH ((NTSTATUS)0xC0000004L)
#endif

/* ---------- Process/Thread information classes (winternl.h on MinGW) ----- */
#ifndef __MINGW32__
#ifndef _PROCESSINFOCLASS
typedef enum _PROCESSINFOCLASS {
    ProcessBasicInformation           = 0,
    ProcessDebugPort                  = 7,
    ProcessWow64Information           = 26,
    ProcessImageFileName              = 27,
    ProcessBreakOnTermination         = 29,
    ProcessSubsystemInformation       = 75,
    ProcessInstrumentationCallback    = 40,
} PROCESSINFOCLASS;
#endif

#ifndef _THREADINFOCLASS
typedef enum _THREADINFOCLASS {
    ThreadBasicInformation            = 0,
    ThreadTimes                       = 1,
    ThreadPriority                    = 2,
    ThreadBasePriority                = 3,
    ThreadAffinityMask                = 4,
    ThreadImpersonationToken          = 5,
    ThreadDescriptorTableEntry        = 6,
    ThreadEnableAlignmentFaultFixup   = 7,
    ThreadEventPair                   = 8,
    ThreadQuerySetWin32StartAddress   = 9,
    ThreadZeroTlsCell                 = 10,
    ThreadPerformanceCount            = 11,
    ThreadAmILastThread               = 12,
    ThreadIdealProcessor              = 13,
    ThreadPriorityBoost               = 14,
    ThreadSetTlsArrayAddress          = 15,
    ThreadIsIoPending                 = 16,
    ThreadHideFromDebugger            = 17,
} THREADINFOCLASS;
#endif
#endif /* !__MINGW32__ */

/* ---------- Memory information class ------------------------------------- */
#ifndef _MEMORY_INFORMATION_CLASS
typedef enum _MEMORY_INFORMATION_CLASS {
    MemoryBasicInformation            = 0,
    MemoryWorkingSetInformation       = 1,
    MemoryMappedFilenameInformation   = 2,
    MemoryRegionInformation           = 3,
    MemoryWorkingSetExInformation     = 4,
    MemorySharedCommitInformation     = 5,
    MemoryImageInformation            = 6,
} MEMORY_INFORMATION_CLASS;
#endif

/* ---------- System information class (winternl.h on MinGW) --------------- */
#ifndef __MINGW32__
#ifndef _SYSTEM_INFORMATION_CLASS
typedef enum _SYSTEM_INFORMATION_CLASS {
    SystemBasicInformation            = 0,
    SystemProcessInformation          = 5,
    SystemModuleInformation           = 11,
    SystemHandleInformation           = 16,
    SystemKernelDebuggerInformation   = 35,
    SystemCodeIntegrityInformation    = 103,
    SystemExtendedHandleInformation   = 64,
} SYSTEM_INFORMATION_CLASS;
#endif

/* ---------- Object information class (winternl.h on MinGW) --------------- */
#ifndef _OBJECT_INFORMATION_CLASS
typedef enum _OBJECT_INFORMATION_CLASS {
    ObjectBasicInformation            = 0,
    ObjectNameInformation             = 1,
    ObjectTypeInformation             = 2,
} OBJECT_INFORMATION_CLASS;
#endif
#endif /* !__MINGW32__ */

/* ---------- Token types (winnt.h on MinGW) -------------------------------- */
#ifndef __MINGW32__
#ifndef _TOKEN_INFORMATION_CLASS
typedef enum _TOKEN_INFORMATION_CLASS {
    TokenUser                         = 1,
    TokenGroups                       = 2,
    TokenPrivileges                   = 3,
    TokenOwner                        = 4,
    TokenPrimaryGroup                 = 5,
    TokenDefaultDacl                  = 6,
    TokenSource                       = 7,
    TokenType                         = 8,
    TokenImpersonationLevel           = 9,
    TokenStatistics                   = 10,
    TokenRestrictedSids               = 11,
    TokenSessionId                    = 12,
    TokenGroupsAndPrivileges          = 13,
    TokenSandBoxInert                 = 15,
    TokenOrigin                       = 17,
    TokenElevationType                = 18,
    TokenLinkedToken                  = 19,
    TokenElevation                    = 20,
    TokenHasRestrictions              = 21,
    TokenAccessInformation            = 22,
    TokenVirtualizationAllowed        = 23,
    TokenVirtualizationEnabled        = 24,
    TokenIntegrityLevel               = 25,
    TokenUIAccess                     = 26,
    TokenMandatoryPolicy              = 27,
    TokenLogonSid                     = 28,
    TokenIsAppContainer               = 29,
} TOKEN_INFORMATION_CLASS;
#endif

#ifndef _TOKEN_TYPE
typedef enum _TOKEN_TYPE {
    TokenPrimary       = 1,
    TokenImpersonation = 2,
} TOKEN_TYPE;
#endif
#endif /* !__MINGW32__ */

/* ---------- Section / MapView types --------------------------------------- */
#ifndef _SECTION_INHERIT
typedef enum _SECTION_INHERIT {
    ViewShare = 1,
    ViewUnmap = 2,
} SECTION_INHERIT;
#endif

#ifndef __MINGW32__  /* ntdef.h on MinGW */
#ifndef _WAIT_TYPE  /* ntdef.h on MinGW */
typedef enum _WAIT_TYPE {
    WaitAll  = 0,
    WaitAny  = 1,
} WAIT_TYPE;
#endif
#endif /* !__MINGW32__ */

/* ---------- PS attributes / create info ---------------------------------- */
#ifndef _PS_ATTRIBUTE_LIST
typedef struct _PS_ATTRIBUTE {
    ULONG_PTR Attribute;
    SIZE_T    Size;
    union {
        ULONG_PTR Value;
        PVOID     ValuePtr;
    };
    PSIZE_T   ReturnLength;
} PS_ATTRIBUTE, *PPS_ATTRIBUTE;

typedef struct _PS_ATTRIBUTE_LIST {
    SIZE_T       TotalLength;
    PS_ATTRIBUTE Attributes[1];
} PS_ATTRIBUTE_LIST, *PPS_ATTRIBUTE_LIST;
#endif

#ifndef _PS_CREATE_INFO
typedef struct _PS_CREATE_INFO {
    SIZE_T  Size;
    ULONG   State;
    union {
        struct {
            ULONG  InitFlags;
            ACCESS_MASK AdditionalFileAccess;
        } InitState;
        struct {
            HANDLE FileHandle;
        } FailSection;
        struct {
            USHORT DllCharacteristics;
        } ExeFormat;
        struct {
            HANDLE IFEOKey;
        } ExeName;
        struct {
            ULONG  OutputFlags;
            ULONG  Flags;
            HANDLE FileHandle;
            HANDLE SectionHandle;
            ULONGLONG UserProcessParametersNative;
            ULONG  UserProcessParametersWow64;
            ULONG  CurrentParameterFlags;
            ULONGLONG PebAddressNative;
            ULONG  PebAddressWow64;
            ULONGLONG ManifestAddress;
            ULONG  ManifestSize;
        } SuccessState;
    };
} PS_CREATE_INFO, *PPS_CREATE_INFO;
#endif

/* ---------- APC / Token types -------------------------------------------- */
typedef VOID (NTAPI *PPS_APC_ROUTINE)(
    PVOID ApcArgument1,
    PVOID ApcArgument2,
    PVOID ApcArgument3
);

#ifndef __MINGW32__  /* winnt.h on MinGW */
#ifndef _TOKEN_PRIVILEGES
typedef struct _TOKEN_PRIVILEGES {
    DWORD             PrivilegeCount;
    LUID_AND_ATTRIBUTES Privileges[ANYSIZE_ARRAY];
} TOKEN_PRIVILEGES, *PTOKEN_PRIVILEGES;
#endif
#endif /* !__MINGW32__ */

/* ---------- Client ID (winternl.h on MinGW) -------------------------------- */
#ifndef __MINGW32__
#ifndef _CLIENT_ID
typedef struct _CLIENT_ID {
    PVOID UniqueProcess;
    PVOID UniqueThread;
} CLIENT_ID, *PCLIENT_ID;
#endif
#endif /* !__MINGW32__ */

/* ---------- IO Status Block (winternl.h on MinGW) ------------------------- */
#ifndef __MINGW32__
#ifndef _IO_STATUS_BLOCK
typedef struct _IO_STATUS_BLOCK {
    union {
        NTSTATUS Status;
        PVOID    Pointer;
    };
    ULONG_PTR Information;
} IO_STATUS_BLOCK, *PIO_STATUS_BLOCK;
#endif
#endif /* !__MINGW32__ */

/* ---------- Security QoS (winnt.h on MinGW) -------------------------------- */
#ifndef __MINGW32__
#ifndef _SECURITY_QUALITY_OF_SERVICE
typedef struct _SECURITY_QUALITY_OF_SERVICE {
    DWORD                        Length;
    SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
    BOOLEAN                      ContextTrackingMode;
    BOOLEAN                      EffectiveOnly;
} SECURITY_QUALITY_OF_SERVICE, *PSECURITY_QUALITY_OF_SERVICE;
#endif
#endif /* !__MINGW32__ */

/* ---------- Timer types (ntdef.h on MinGW) -------------------------------- */
#ifndef __MINGW32__
#ifndef _TIMER_TYPE
typedef enum _TIMER_TYPE {
    NotificationTimer = 0,
    SynchronizationTimer = 1,
} TIMER_TYPE;
#endif
#endif /* !__MINGW32__ */

/* =========================================================================
 *  SW4 Internal structures used by the runtime
 * ========================================================================= */

/* Entry in the static SSN lookup table */
typedef struct _SW4_mingw_SSN_ENTRY {
    DWORD  Count;
    struct {
        DWORD Build;
        DWORD Ssn;
    } Entries[64];
} SW4_mingw_SSN_ENTRY;

/* Export entry used during FreshyCalls / Hell's Gate scanning */
typedef struct _SW4_mingw_EXPORT {
    PVOID Address;
    DWORD Hash;
    DWORD Ordinal;
} SW4_mingw_EXPORT, *PSW4_mingw_EXPORT;

#endif /* SW4_mingw_SYSCALLS_TYPES_H */
