/*
 * SW4_msvcSyscalls.h -- generated by SysWhispers4
 * DO NOT EDIT -- regenerate with syswhispers.py
 */
#pragma once
#ifndef SW4_msvc_SYSCALLS_H
#define SW4_msvc_SYSCALLS_H

#include "SW4_msvcSyscalls_Types.h"

#ifdef __cplusplus
extern "C" {
#endif

/* =========================================================================
 *  Runtime initialization
 *  FreshyCalls -- sorts ntdll Nt* exports by VA
 * ========================================================================= */
EXTERN_C BOOL SW4_msvc_Initialize(VOID);


/* =========================================================================
 *  Syscall function prototypes
 * ========================================================================= */
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtAllocateVirtualMemory(HANDLE ProcessHandle, PVOID* BaseAddress, ULONG_PTR ZeroBits, PSIZE_T RegionSize, ULONG AllocationType, ULONG Protect);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtFreeVirtualMemory(HANDLE ProcessHandle, PVOID* BaseAddress, PSIZE_T RegionSize, ULONG FreeType);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtWriteVirtualMemory(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T NumberOfBytesToWrite, PSIZE_T NumberOfBytesWritten);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtReadVirtualMemory(HANDLE ProcessHandle, PVOID BaseAddress, PVOID Buffer, SIZE_T NumberOfBytesToRead, PSIZE_T NumberOfBytesRead);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtProtectVirtualMemory(HANDLE ProcessHandle, PVOID* BaseAddress, PSIZE_T RegionSize, ULONG NewProtect, PULONG OldProtect);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtCreateThreadEx(PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, HANDLE ProcessHandle, PVOID StartRoutine, PVOID Argument, ULONG CreateFlags, SIZE_T ZeroBits, SIZE_T StackSize, SIZE_T MaximumStackSize, PPS_ATTRIBUTE_LIST AttributeList);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtOpenProcess(PHANDLE ProcessHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PCLIENT_ID ClientId);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtOpenThread(PHANDLE ThreadHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PCLIENT_ID ClientId);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtSuspendThread(HANDLE ThreadHandle, PULONG PreviousSuspendCount);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtResumeThread(HANDLE ThreadHandle, PULONG SuspendCount);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtGetContextThread(HANDLE ThreadHandle, PCONTEXT ThreadContext);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtSetContextThread(HANDLE ThreadHandle, PCONTEXT ThreadContext);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtUnmapViewOfSection(HANDLE ProcessHandle, PVOID BaseAddress);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtMapViewOfSection(HANDLE SectionHandle, HANDLE ProcessHandle, PVOID* BaseAddress, ULONG_PTR ZeroBits, SIZE_T CommitSize, PLARGE_INTEGER SectionOffset, PSIZE_T ViewSize, SECTION_INHERIT InheritDisposition, ULONG AllocationType, ULONG Win32Protect);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtCreateSection(PHANDLE SectionHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, PLARGE_INTEGER MaximumSize, ULONG SectionPageProtection, ULONG AllocationAttributes, HANDLE FileHandle);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtQueueApcThread(HANDLE ThreadHandle, PPS_APC_ROUTINE ApcRoutine, PVOID ApcArgument1, PVOID ApcArgument2, PVOID ApcArgument3);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtQueueApcThreadEx(HANDLE ThreadHandle, HANDLE ReserveHandle, PPS_APC_ROUTINE ApcRoutine, PVOID ApcArgument1, PVOID ApcArgument2, PVOID ApcArgument3);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtAlertResumeThread(HANDLE ThreadHandle, PULONG PreviousSuspendCount);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtTestAlert();
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtClose(HANDLE Handle);
EXTERN_C NTSTATUS NTAPI SW4_msvc_NtWaitForSingleObject(HANDLE Handle, BOOLEAN Alertable, PLARGE_INTEGER Timeout);

#ifdef __cplusplus
}
#endif

#endif /* SW4_msvc_SYSCALLS_H */
